apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: http-autoscaler
  #namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: my-np-service
      metricName: http_request
      targetValue: 10  #no.of http-request
