---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  namespace: monitoring 
  labels:
    app: my-app
    tier: Dev
    deployment: v1
spec:
  containers: 
    - name: naginx-1
      image: nginx
      ports: 
        - containerPort: 80
---    
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  namespace: monitoring
  labels:
    app: my-app
    tier: QA
    deployment: v1
spec:
  containers: 
    - name: nginx-2
      image: nginx
      ports: 
        - containerPort: 80
---   
apiVersion: v1
kind: Pod
metadata:
  name: nginx-3
  namespace: monitoring
  labels:
    app: my-app
    tier: Prod
    deployment: v1
spec:
  containers: 
    - name: nginx-3
      image: nginx
      ports: 
        - containerPort: 80
   


