apiVersion: v1
kind: Service
metadata:
  name: np-service
  #namespace: monitoring 
spec:
  type: NodePort
  selector:
    app: Gps
    department: Test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

